[package]
name = "lnx-controller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lnx-storage = { path = "../lnx-storage" }
lnx-common = { path = "../lnx-common" }

scylladb-backend = { path = "../storage-backends/scylladb-backend" }

tokio = { version = "1", features = ["rt"] }
serde = { version = "1", features = ["derive"] }
uuid = { version = "0.8.1", features = ["v4"] }

tracing = "0.1.29"
tracing-futures = "0.2.5"
anyhow = "1"
serde_json = "1"
once_cell = "1.10.0"
dashmap = "5.1.0"
